-- ============================================================================
-- Beautrium OMS — reset transactional/test data for a fresh UAT round
-- ============================================================================
-- Scope (as confirmed): clears Orders and everything downstream that was
-- generated by testing — imports, consolidation, assignment, picker
-- completions, admin verification, and the order-related audit/status trail.
--
-- KEPT untouched: warehouses, employees_users (and their Supabase Auth
-- logins), locations (Location Master), reason_master, configuration,
-- export_jobs, purge_log. You do NOT need to recreate users or re-upload
-- Location Master after running this — only Order import needs to happen
-- again.
--
-- Run this in Supabase Studio → SQL Editor. It is IRREVERSIBLE — there is no
-- undo once these rows are gone.
-- ============================================================================

begin;

-- All of Order Core + both product modules' transactional tables, truncated
-- together so the various FK references between them (orders <-> batches)
-- don't block each other. CASCADE is a safety net, not expected to reach
-- beyond this list — nothing outside it references these tables by a real FK.
truncate table
  picker_completion_lines,
  picker_completions,
  admin_verifications,
  assignment_orders,
  assignment_batches,
  consolidation_orders,
  consolidation_batches,
  order_lines,
  orders,
  import_errors,
  import_batches
restart identity cascade;

-- Audit trail / status history: remove only the entries about the data just
-- cleared, keep everything about users/locations/reason master/configuration.
delete from audit_logs
  where entity_type in ('orders', 'import_batches', 'consolidation_batches', 'assignment_batches');
delete from status_history
  where entity_type in ('orders', 'import_batches', 'consolidation_batches', 'assignment_batches');

commit;

-- ---------------------------------------------------------------------------
-- Verify: every row count below should be 0. warehouses/employees_users/
-- locations/reason_master/configuration are intentionally not listed here
-- because they should NOT be 0.
-- ---------------------------------------------------------------------------
select
  (select count(*) from orders)                    as orders,
  (select count(*) from order_lines)                as order_lines,
  (select count(*) from import_batches)             as import_batches,
  (select count(*) from import_errors)              as import_errors,
  (select count(*) from consolidation_batches)      as consolidation_batches,
  (select count(*) from consolidation_orders)       as consolidation_orders,
  (select count(*) from assignment_batches)         as assignment_batches,
  (select count(*) from assignment_orders)          as assignment_orders,
  (select count(*) from picker_completions)         as picker_completions,
  (select count(*) from picker_completion_lines)    as picker_completion_lines,
  (select count(*) from admin_verifications)        as admin_verifications;
